In [315]:
import pandas as pd
from pandas import get_dummies
import numpy as numpy
import sklearn
import xgboost

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [316]:
df = pd.read_csv('/Users/kayodew/Desktop/supply_chain_ml_project/DataCoSupplyChainDataset.csv',encoding="latin1")

# 01 Data Understanding

In [317]:
df.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,EE. UU.,XXXXXXXXX,Kimberly,19488,Flowers,XXXXXXXXX,Consumer,NY,2122 Hazy Corner,14150.0,2,Fitness,43.013969,-78.879066,Pacific Asia,Toowoomba,Australia,19488,1/13/2018 11:03,75935,1360,32.779999,0.10,179250,327.75,0.06,1,327.75,294.980011,18.580000,Oceania,Queensland,CANCELED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Constance,19487,Terrell,XXXXXXXXX,Home Office,PR,1879 Green Pine Bank,725.0,2,Fitness,18.242538,-66.037056,Pacific Asia,Guangzhou,China,19487,1/13/2018 10:42,75934,1360,39.330002,0.12,179249,327.75,0.33,1,327.75,288.420013,95.180000,Eastern Asia,Guangdong,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,EE. UU.,XXXXXXXXX,Erica,19486,Stevens,XXXXXXXXX,Corporate,FL,7595 Cotton Log Row,33162.0,2,Fitness,25.928869,-80.162872,Pacific Asia,Guangzhou,China,19486,1/13/2018 10:21,75933,1360,42.610001,0.13,179248,327.75,0.24,1,327.75,285.140015,68.430000,Eastern Asia,Guangdong,PROCESSING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Nichole,19485,Olsen,XXXXXXXXX,Corporate,PR,2051 Dusty Route,725.0,2,Fitness,18.233223,-66.037056,Pacific Asia,Guangzhou,China,19485,1/13/2018 10:00,75932,1360,49.160000,0.15,179247,327.75,0.48,1,327.75,278.589996,133.720001,Eastern Asia,Guangdong,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,EE. UU.,XXXXXXXXX,Oprah,19484,Delacruz,XXXXXXXXX,Corporate,CA,9139 Blue Blossom Court,94583.0,2,Fitness,37.773991,-121.966629,Pacific Asia,Guangzhou,China,19484,1/13/2018 9:39,75931,1360,52.439999,0.16,179246,327.75,0.48,1,327.75,275.309998,132.149994,Eastern Asia,Guangdong,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [318]:
# let's see how many rows and cols exist in the da.
print(df.shape[0])
print(df.shape[1])

180519
53

In [319]:
#Trick to tell a quick summary of the data.

pd.DataFrame({
    'column': df.columns,
    'dtype': df.dtypes.astype(str),
    'non_null_count': df.count().values,
    'missing_count': df.isnull().sum().values,
    'unique_values': df.nunique().values
})

,column,dtype,non_null_count,missing_count,unique_values
Type,Type,str,180519,0,4
Days for shipping (real),Days for shipping (real),int64,180519,0,7
Days for shipment (scheduled),Days for shipment (scheduled),int64,180519,0,4
Benefit per order,Benefit per order,float64,180519,0,21998
Sales per customer,Sales per customer,float64,180519,0,2927
Delivery Status,Delivery Status,str,180519,0,4
Late_delivery_risk,Late_delivery_risk,int64,180519,0,2
Category Id,Category Id,int64,180519,0,51
Category Name,Category Name,str,180519,0,50
Customer City,Customer City,str,180519,0,563
Customer Country,Customer Country,str,180519,0,2
Customer Email,Customer Email,str,180519,0,1
Customer Fname,Customer Fname,str,180519,0,782
Customer Id,Customer Id,int64,180519,0,20652
Customer Lname,Customer Lname,str,180511,8,1109
Customer Password,Customer Password,str,180519,0,1
Customer Segment,Customer Segment,str,180519,0,3
Customer State,Customer State,str,180519,0,46
Customer Street,Customer Street,str,180519,0,7458
Customer Zipcode,Customer Zipcode,float64,180516,3,995
Department Id,Department Id,int64,180519,0,11
Department Name,Department Name,str,180519,0,11
Latitude,Latitude,float64,180519,0,11250
Longitude,Longitude,float64,180519,0,4487
Market,Market,str,180519,0,5
Order City,Order City,str,180519,0,3597
Order Country,Order Country,str,180519,0,164
Order Customer Id,Order Customer Id,int64,180519,0,20652
order date (DateOrders),order date (DateOrders),str,180519,0,65752
Order Id,Order Id,int64,180519,0,65752
Order Item Cardprod Id,Order Item Cardprod Id,int64,180519,0,118
Order Item Discount,Order Item Discount,float64,180519,0,1017
Order Item Discount Rate,Order Item Discount Rate,float64,180519,0,18
Order Item Id,Order Item Id,int64,180519,0,180519
Order Item Product Price,Order Item Product Price,float64,180519,0,75
Order Item Profit Ratio,Order Item Profit Ratio,float64,180519,0,162
Order Item Quantity,Order Item Quantity,int64,180519,0,5
Sales,Sales,float64,180519,0,193
Order Item Total,Order Item Total,float64,180519,0,2927
Order Profit Per Order,Order Profit Per Order,float64,180519,0,21998
Order Region,Order Region,str,180519,0,23
Order State,Order State,str,180519,0,1089
Order Status,Order Status,str,180519,0,9
Order Zipcode,Order Zipcode,float64,24840,155679,609
Product Card Id,Product Card Id,int64,180519,0,118
Product Category Id,Product Category Id,int64,180519,0,51
Product Description,Product Description,float64,0,180519,0
Product Image,Product Image,str,180519,0,118
Product Name,Product Name,str,180519,0,118
Product Price,Product Price,float64,180519,0,75
Product Status,Product Status,int64,180519,0,1
shipping date (DateOrders),shipping date (DateOrders),str,180519,0,63701
Shipping Mode,Shipping Mode,str,180519,0,4

### Checking Null Fields

In [320]:
df.isnull().sum().sort_values(ascending = False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Order Id                              0
Order Country                         0
Order Customer Id                     0
Customer Fname                        0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Id                           0
Days for shipping (real)              0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Shipping Mode                         0
dtype: int64

All these fields would be handled once we hit the drop phase of this project which means the dataset is fairly clean for the project.

# 02 DATA CLEANING

In [321]:
# Trick to quickly spot high and low  cardinality fields 
df.nunique().sort_values(ascending=False)

Order Item Id                    180519
Order Id                          65752
order date (DateOrders)           65752
shipping date (DateOrders)        63701
Benefit per order                 21998
Order Profit Per Order            21998
Order Customer Id                 20652
Customer Id                       20652
Latitude                          11250
Customer Street                    7458
Longitude                          4487
Order City                         3597
Order Item Total                   2927
Sales per customer                 2927
Customer Lname                     1109
Order State                        1089
Order Item Discount                1017
Customer Zipcode                    995
Customer Fname                      782
Order Zipcode                       609
Customer City                       563
Sales                               193
Order Country                       164
Order Item Profit Ratio             162
Product Card Id                     118
Order Item Cardprod Id              118
Product Image                       118
Product Name                        118
Product Price                        75
Order Item Product Price             75
Category Id                          51
Product Category Id                  51
Category Name                        50
Customer State                       46
Order Region                         23
Order Item Discount Rate             18
Department Name                      11
Department Id                        11
Order Status                          9
Days for shipping (real)              7
Order Item Quantity                   5
Market                                5
Type                                  4
Delivery Status                       4
Days for shipment (scheduled)         4
Shipping Mode                         4
Customer Segment                      3
Customer Country                      2
Late_delivery_risk                    2
Customer Password                     1
Customer Email                        1
Product Status                        1
Product Description                   0
dtype: int64

In [322]:
# Trying to understand what some firlds contain might give us a good understanding of what to drop or keep
df['Product Name'].unique()
df['Category Name'].unique() #or .nunique to see the count of unique values

<StringArray>
[      'Sporting Goods',               'Cleats',        'Shop By Sport',
      'Women's Apparel',          'Electronics',         'Boxing & MMA',
     'Cardio Equipment',             'Trade-In',     'Kids' Golf Clubs',
   'Hunting & Shooting',  'Baseball & Softball',       'Men's Footwear',
     'Camping & Hiking', 'Consumer Electronics',             'Cameras ',
            'Computers',           'Basketball',               'Soccer',
       'Girls' Apparel',          'Accessories',     'Women's Clothing',
               'Crafts',       'Men's Clothing',     'Tennis & Racquet',
  'Fitness Accessories',      'As Seen on  TV!',           'Golf Balls',
    'Strength Training',  'Children's Clothing',             'Lacrosse',
                'Baby ',              'Fishing',               'Books ',
                 'DVDs',                 'CDs ',               'Garden',
               'Hockey',         'Pet Supplies',    'Health and Beauty',
                'Music',          'Video Games',          'Golf Gloves',
    'Golf Bags & Carts',           'Golf Shoes',         'Golf Apparel',
   'Women's Golf Clubs',     'Men's Golf Clubs',                 'Toys',
         'Water Sports', 'Indoor/Outdoor Games']
Length: 50, dtype: str

In [323]:
#We this point, need to drop some redundant fields that would not be needed.
# Fields that exhibit traits of high cardinality should rightly be dropped. 
df = df.drop(columns=['Category Id','order date (DateOrders)',
                      'Order Customer Id','shipping date (DateOrders)',
                     'Department Id','Product Image',
                      'Customer Email','Customer Zipcode','Product Category Id','Product Description',
                       'Customer Fname','Customer Street','Product Card Id',
                        'Customer Lname','Customer State','Order Zipcode',
                         'Customer Password','Customer Id',
                         'Order Id','Order Item Cardprod Id','Product Status'
                         ])

In [324]:
# Next would be a trick to clean the column names, remove white spaces and set everything to lowercaps
df.columns = [each.lower().replace(' ', '_') for each in df.columns]

In [325]:
df.columns.tolist()

['type',
 'days_for_shipping_(real)',
 'days_for_shipment_(scheduled)',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_segment',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'product_name',
 'product_price',
 'shipping_mode']

Since the fields are clean, there would be no need to replace any missing value.

# 03 Data Encoding

In [326]:
df.dtypes.to_frame() # To help see the full view. Works better than just using dtypes.

                                     0
type                               str
days_for_shipping_(real)         int64
days_for_shipment_(scheduled)    int64
benefit_per_order              float64
sales_per_customer             float64
delivery_status                    str
late_delivery_risk               int64
category_name                      str
customer_city                      str
customer_country                   str
customer_segment                   str
department_name                    str
latitude                       float64
longitude                      float64
market                             str
order_city                         str
order_country                      str
order_item_discount            float64
order_item_discount_rate       float64
order_item_id                    int64
order_item_product_price       float64
order_item_profit_ratio        float64
order_item_quantity              int64
sales                          float64
order_item_total               float64
order_profit_per_order         float64
order_region                       str
order_state                        str
order_status                       str
product_name                       str
product_price                  float64
shipping_mode                      str

In [327]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_name', 'customer_city',
       'customer_country', 'customer_segment', 'department_name', 'latitude',
       'longitude', 'market', 'order_city', 'order_country',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_name', 'product_price', 'shipping_mode'],
      dtype='str')

In [328]:
print(df.type.unique())
print(df.delivery_status.unique())
print(df.shipping_mode.unique())
print(df.order_status.unique())
print(df.customer_segment.unique())

<StringArray>
['DEBIT', 'TRANSFER', 'CASH', 'PAYMENT']
Length: 4, dtype: str
<StringArray>
['Advance shipping', 'Late delivery', 'Shipping on time', 'Shipping canceled']
Length: 4, dtype: str
<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str
<StringArray>
[       'COMPLETE',         'PENDING',          'CLOSED', 'PENDING_PAYMENT',
        'CANCELED',      'PROCESSING', 'SUSPECTED_FRAUD',         'ON_HOLD',
  'PAYMENT_REVIEW']
Length: 9, dtype: str
<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

In [329]:
df.head(2)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_city,customer_country,customer_segment,department_name,latitude,longitude,market,order_city,order_country,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_state,order_status,product_name,product_price,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Consumer,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Consumer,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,Smart watch,327.75,Standard Class

In [330]:
df.columns

Index(['type', 'days_for_shipping_(real)', 'days_for_shipment_(scheduled)',
       'benefit_per_order', 'sales_per_customer', 'delivery_status',
       'late_delivery_risk', 'category_name', 'customer_city',
       'customer_country', 'customer_segment', 'department_name', 'latitude',
       'longitude', 'market', 'order_city', 'order_country',
       'order_item_discount', 'order_item_discount_rate', 'order_item_id',
       'order_item_product_price', 'order_item_profit_ratio',
       'order_item_quantity', 'sales', 'order_item_total',
       'order_profit_per_order', 'order_region', 'order_state', 'order_status',
       'product_name', 'product_price', 'shipping_mode'],
      dtype='str')

Observation shows that we can't perform lable or manual encoding on these fields, 
they are not ordinal so no assignment can be given to them.

We will thus perform one-hot encoding against them. 

It is imperative to take out those fields with high cardinality.

In [331]:
df[['type','delivery_status','category_name',
    'customer_city','customer_country','customer_segment',
    'department_name','market','order_city','order_country',
    'order_region',	'order_state','order_status','product_name','shipping_mode']].nunique()

type                   4
delivery_status        4
category_name         50
customer_city        563
customer_country       2
customer_segment       3
department_name       11
market                 5
order_city          3597
order_country        164
order_region          23
order_state         1089
order_status           9
product_name         118
shipping_mode          4
dtype: int64

In [332]:
df[['type','delivery_status','category_name',
    'customer_city','customer_country','customer_segment',
    'department_name','market','order_city','order_country',
    'order_region',	'order_state','order_status','product_name','shipping_mode']].nunique()

type                   4
delivery_status        4
category_name         50
customer_city        563
customer_country       2
customer_segment       3
department_name       11
market                 5
order_city          3597
order_country        164
order_region          23
order_state         1089
order_status           9
product_name         118
shipping_mode          4
dtype: int64

We will further drop ['customer_city', 'order_city','order_state','product_name'] as they have the potential to blow up the dataset.

In [333]:
df = df.drop(columns=
    ['customer_city', 'order_city','order_state','order_country','product_name'])

In [334]:
print(f'The dataframe now has {df.shape[1]} columns.')

The dataframe now has 27 columns.

At this point, we would separate the target variables from the entire dataset.  

Once this is done, we would drop the fields from the dataset. The reason for this is simply to prevent target leakage, which is a case where the model learns perfectly from the general dataset.

In [335]:
# Target feature for Fraud cases
df.head(2)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_country,customer_segment,department_name,latitude,longitude,market,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,order_status,product_price,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Puerto Rico,Consumer,Fitness,18.251453,-66.037056,Pacific Asia,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,COMPLETE,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Puerto Rico,Consumer,Fitness,18.279451,-66.037064,Pacific Asia,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,PENDING,327.75,Standard Class

In [336]:
print(df.order_status.unique())
print(df.delivery_status.unique())

<StringArray>
[       'COMPLETE',         'PENDING',          'CLOSED', 'PENDING_PAYMENT',
        'CANCELED',      'PROCESSING', 'SUSPECTED_FRAUD',         'ON_HOLD',
  'PAYMENT_REVIEW']
Length: 9, dtype: str
<StringArray>
['Advance shipping', 'Late delivery', 'Shipping on time', 'Shipping canceled']
Length: 4, dtype: str

In [337]:
#Fraud cases
fraud_df = df.copy()

y_fraud = (fraud_df['order_status'] == 'SUSPECTED_FRAUD').astype(int) #converts T or F to 1 and 0
x_fraud = fraud_df.drop(columns=['order_status'])

In [338]:
#Late Delivery
late_delivery_df = df.copy()

y_late_d = (late_delivery_df['late_delivery_risk'] == 1).astype(int)
x_late_d = late_delivery_df.drop(columns=['late_delivery_risk','delivery_status' ])

In [339]:
#Order Disruption
disruption_df = df.copy()

y_disruption= disruption_df['order_status'].isin(['ON_HOLD',
                                        'PAYMENT_REVIEW', 'CANCELED']).astype(int)
x_disruption = disruption_df.drop(columns=['order_status'])

For business disruption, we consider only some of the statuses.

The logic behind this is quite straight forward
:
CANCELED: The order didn't complete. That's a disruption.

ON_HOLD: Something stopped the order from moving forward. That's a disruption.

PAYMENT_REVIEW: The payment is flagged and under investigation. That's a disruption.

PENDING, PROCESSING, PENDING_PAYMENT are all just normal stages in an order lifecycle. Every order goes through something like those states. Including them would mean your model is essentially predicting "is this order being processed normally"; which isn't what disruption means.

In [340]:
print('Fraud'); print(y_fraud.value_counts()); print('\n')
print('Late Delivery'); print(y_late_d.value_counts()); print('\n')
print('Disruption'); print(y_disruption.value_counts())

Fraud
order_status
0    176457
1      4062
Name: count, dtype: int64


Late Delivery
late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64


Disruption
order_status
0    165130
1     15389
Name: count, dtype: int64

Now we can move on to encoding.

# 04 Data Encoding

In [341]:
x_disruption.head(2)

,type,days_for_shipping_(real),days_for_shipment_(scheduled),benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_name,customer_country,customer_segment,department_name,latitude,longitude,market,order_item_discount,order_item_discount_rate,order_item_id,order_item_product_price,order_item_profit_ratio,order_item_quantity,sales,order_item_total,order_profit_per_order,order_region,product_price,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,Sporting Goods,Puerto Rico,Consumer,Fitness,18.251453,-66.037056,Pacific Asia,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,Sporting Goods,Puerto Rico,Consumer,Fitness,18.279451,-66.037064,Pacific Asia,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,327.75,Standard Class

In [ ]:
### Encoding 1 - Fruad
x_fraud = get_dummies(x_fraud,columns=[
    'type','delivery_status','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'shipping_mode'],
    dtype=int,drop_first = True)

In [ ]:
### Encoding 2 -  Late Delivery 
x_late_d = get_dummies(x_late_d,columns=[
    'type','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'order_status','shipping_mode'],
    dtype=int,drop_first = True)

In [ ]:
### Encoding 3 - Order Disruption
x_disruption = get_dummies(x_disruption,columns=[
    'type','delivery_status','category_name','customer_country','customer_segment',
    'department_name','market',
    'order_region',	'shipping_mode'],
    dtype=int,drop_first = True)

In [349]:
print(f'Suspected fraud: {x_fraud.shape[1]}')
print('\n')
print(f'Late Delivery: {x_late_d.shape[1]}')
print('\n')
print(f'Order Disruptions: {x_disruption.shape[1]}')

Suspected fraud: 114


Late Delivery: 118


Order Disruptions: 114